[package]
name = "sysfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.28.2"
crossterm = "0.26"
display-info = "0.4.3"
libc = "0.2.148"
